### ISSUE TITLE
AJAX pagination functionality

### ISSUE THREAD

**Issue by jackeel** [armando7818/CSE-136-HW3#9]
General descriptions of pagination functionality that need to be added.
1. Insert bookmark on any list
   - if a bookmark is added to an already-full (i.e. 9 bookmarks) page, it should be added to a new pagination.
2. Unstar bookmark when viewing starred list
   - if a bookmark is unstarred and it is the last one on a page, the current page should probably be removed and the view changed to a previous pagination (or some other logical alternative)
3. Delete bookmark on any list
   - similar to above. if a bookmark is deleted and it is the last one on a page, the current page should probably be removed and the view changed to a previous pagination (or some other logical alternative)
4. Edit bookmark
   - similar to above. if a bookmark is edited out of the current folder (i.e. current folder is 5, and the bookmark's folder_id is edited from 5 to 4), and it is the last one on the page, the current page should probably be removed and the view changed to a previous pagination (or some other logical alternative).

A corner case is when there's only one page. Whoever fixes these will have to decide whether to show pagination by default (e.g. show a **1** for the first page, even if there's no bookmarks), and to do so consistently in all scenarios.

This combines issues #4 and #8 . The spots where these should probably be fixed are noted with TODO in index.js

**Comment by yczhu** [comment]
The way I fixed these issues.
1. Insert bookmark on any list
   - Check the current page, if it is full, no updates on the bookmarks.
   - Update the pagination bar. It is possible that the pagination number grow by 1 due to the insertion.
2. Unstar bookmark when viewing starred list
   - Update the current bookmarks being displayed.
   - Update the pagination bar.
3. Delete bookmark on any list
   - Update the current bookmarks being displayed.
   - Update the pagination bar.
4. Edit bookmark
   If edit to another folder:
   - Update the current bookmarks being displayed.
   - Update the pagination bar.
     Added two functions `updateBookmarks()` and `updatePagination()` to avoid repeating codes.
